CREATE TABLE `SYS_LOG`
 (   `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
 `USERNAME` varchar(255) DEFAULT NULL COMMENT '用户名',
 `OPERATION` varchar(255) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '操作描述',
 `TIME` int(11) DEFAULT NULL COMMENT '响应时间',
 `METHOD` varchar(255) DEFAULT NULL COMMENT '请求方法名',
 `PARAMS` varchar(1000) DEFAULT NULL COMMENT '请求方法参数',
 `IP` varchar(255) DEFAULT NULL COMMENT '操作人IP',
 `CREATE_TIME` datetime DEFAULT NULL COMMENT '操作时间',
 PRIMARY KEY (`ID`)
 ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='审计日志表'